In [1]:
import pandas as pd

wine2 = pd.read_csv('wine_clean.csv')

wine_winery = wine2[['province', 'points', 'price', 'variety']]
winex4 = pd.get_dummies(wine_winery, drop_first=True)

y4 = winex4['points'].values
X4 = winex4.drop('points', axis=1).values

In [10]:
from pycaret.regression import *

exp_reg = setup(wine_winery, target = 'points')

Setup Succesfully Completed!

In [4]:
compare_models()

IntProgress(value=0, description='Processing: ', max=245)

Initiated  . . . . . . . . . . . . . . . . . .               20:53:47
Status     . . . . . . . . . . . . . . . . . .  Compiling Final Model
ETC        . . . . . . . . . . . . . . . . . .  0.0 Seconds Remaining

,Model,MAE,MSE,RMSE,R2,RMSLE,MAPE
0,Ridge Regression,2.001400e+00,6.339100e+00,2.517500e+00,3.118000e-01,0.0281,0.0227
1,Bayesian Ridge,2.002400e+00,6.340100e+00,2.517700e+00,3.117000e-01,0.0281,0.0227
2,Least Angle Regression,2.006200e+00,6.361000e+00,2.521800e+00,3.094000e-01,0.0281,0.0227
3,Orthogonal Matching Pursuit,2.017000e+00,6.425400e+00,2.534600e+00,3.024000e-01,0.0283,0.0229
4,Elastic Net,2.130500e+00,7.154100e+00,2.674400e+00,2.233000e-01,0.0298,0.0241
5,Lasso Regression,2.131900e+00,7.154700e+00,2.674500e+00,2.232000e-01,0.0298,0.0242
6,Lasso Least Angle Regression,2.478000e+00,9.210500e+00,3.034700e+00,-1.000000e-04,0.0340,0.0281
7,Passive Aggressive Regressor,2.797800e+00,1.912700e+01,4.265300e+00,-1.086700e+00,0.0434,0.0313
8,Random Sample Consensus,3.197362e+06,3.270571e+16,1.325290e+08,-3.595474e+15,0.6335,36659.0528
9,Linear Regression,2.933957e+06,5.080542e+16,1.224214e+08,-5.569901e+15,0.3904,33615.3896

KeyboardInterrupt:

In [11]:
ridge = create_model('ridge')

         MAE     MSE    RMSE      R2   RMSLE    MAPE
0     2.0443  6.6810  2.5848  0.2940  0.0288  0.0232
1     2.0383  6.5386  2.5571  0.2928  0.0285  0.0231
2     2.0037  6.3407  2.5181  0.3050  0.0281  0.0227
3     2.0167  6.4246  2.5347  0.2996  0.0282  0.0228
4     1.9927  6.3011  2.5102  0.3284  0.0281  0.0226
5     1.9861  6.2349  2.4970  0.3135  0.0278  0.0225
6     1.9845  6.2029  2.4906  0.3255  0.0279  0.0225
7     2.0384  6.4850  2.5466  0.3067  0.0284  0.0231
8     2.0039  6.4776  2.5451  0.2863  0.0283  0.0227
9     2.0297  6.5047  2.5504  0.3171  0.0285  0.0230
Mean  2.0138  6.4191  2.5334  0.3069  0.0283  0.0228
SD    0.0216  0.1410  0.0278  0.0134  0.0003  0.0002

In [12]:
tuned_ridge = tune_model('ridge')

         MAE     MSE    RMSE      R2   RMSLE    MAPE
0     2.0444  6.6832  2.5852  0.2937  0.0288  0.0232
1     2.0387  6.5412  2.5576  0.2925  0.0285  0.0231
2     2.0043  6.3446  2.5189  0.3046  0.0282  0.0227
3     2.0171  6.4264  2.5350  0.2994  0.0282  0.0228
4     1.9924  6.3015  2.5103  0.3284  0.0281  0.0226
5     1.9866  6.2383  2.4977  0.3131  0.0278  0.0225
6     1.9850  6.2072  2.4914  0.3250  0.0279  0.0225
7     2.0385  6.4865  2.5469  0.3065  0.0284  0.0231
8     2.0044  6.4801  2.5456  0.2860  0.0283  0.0227
9     2.0302  6.5077  2.5510  0.3167  0.0285  0.0230
Mean  2.0142  6.4217  2.5340  0.3066  0.0283  0.0228
SD    0.0216  0.1406  0.0277  0.0134  0.0003  0.0002

In [13]:
lasso = create_model('llar')

         MAE     MSE    RMSE      R2   RMSLE    MAPE
0     2.5074  9.4641  3.0764 -0.0002  0.0344  0.0284
1     2.4921  9.2491  3.0412 -0.0003  0.0340  0.0282
2     2.4613  9.1250  3.0208 -0.0001  0.0338  0.0279
3     2.4833  9.1736  3.0288 -0.0001  0.0339  0.0281
4     2.5093  9.3849  3.0635 -0.0003  0.0343  0.0285
5     2.4574  9.0816  3.0136 -0.0000  0.0337  0.0278
6     2.4592  9.1975  3.0327 -0.0001  0.0340  0.0279
7     2.4981  9.3558  3.0587 -0.0003  0.0342  0.0283
8     2.4585  9.0786  3.0131 -0.0003  0.0338  0.0279
9     2.5193  9.5246  3.0862 -0.0000  0.0345  0.0285
Mean  2.4846  9.2635  3.0435 -0.0002  0.0341  0.0281
SD    0.0228  0.1519  0.0249  0.0001  0.0003  0.0002

In [14]:
tuned_lasso = tune_model('llar')

         MAE     MSE    RMSE      R2   RMSLE    MAPE
0     2.0469  6.6931  2.5871  0.2927  0.0288  0.0232
1     2.0397  6.5466  2.5586  0.2920  0.0285  0.0231
2     2.0037  6.3347  2.5169  0.3057  0.0281  0.0227
3     2.0194  6.4394  2.5376  0.2980  0.0283  0.0229
4     1.9972  6.3180  2.5136  0.3266  0.0281  0.0227
5     1.9868  6.2285  2.4957  0.3142  0.0278  0.0225
6     1.9866  6.2106  2.4921  0.3247  0.0279  0.0225
7     2.0397  6.4858  2.5467  0.3066  0.0284  0.0231
8     2.0048  6.4842  2.5464  0.2856  0.0283  0.0227
9     2.0289  6.4958  2.5487  0.3180  0.0285  0.0230
Mean  2.0154  6.4237  2.5343  0.3064  0.0283  0.0228
SD    0.0214  0.1426  0.0281  0.0136  0.0003  0.0002